extract_task:
  description: >
    Conduct a thorough research about {content}
    Extract project names and their related technologies.
  expected_output: >
    A list of project names and their related technologies extracted from {content}
  agent: extract_agent

news_finder_task:
  description: >
    Locate and deliver a latest news about the technologies identified by extract_agent, excluding project information.
    Ensure the information is summary and covers all relevant aspects.
  expected_output: >
    Summary news about the technologies identified by extract_agent, excluding project information, covering all relevant aspects.
  agent: news_agent

blog_writer_task:
  description: >
    Craft compelling content on tech advancements based on the information provided by news_finder_task.
    Ensure the content is engaging, informative, and tailored to the target audience, without mentioning any project names.
  expected_output: >
    A well-crafted blog post on tech advancements based on the information provided by news_finder_task, without mentioning any project names.
  agent: blog_writer
