extract_task:
  description: >
    Conduct a thorough research about {topic}
    Extract project names and their related technologies.
  expected_output: >
    A list of project names and their related technologies extracted from {topic}
  agent: extract_agent

news_finder_task:
  description: >
    Find and provide detailed information about only the technologies extracted by extract_agent not project.
    Ensure the information is comprehensive and covers all relevant aspects.
  expected_output: >
    Detailed information about only the technologies extracted by extract_agent not project, covering all relevant aspects.
  agent: news_agent
